package com.knightlore.client;

public enum ClientState {
  MAIN_MENU,
  LOBBY_MENU,
  PRE_EDITOR,
  LEVEL_EDITOR,
  TESTING_LEVEL,
  NAMING_LEVEL,
  LOADING_LEVEL_TO_EDIT,
  LOADING_LEVEL_TO_PLAY,
  OPTIONS_MENU,
  LOBBY,
  GAME,
  END
}
